---
name: trivyignore-validator
description: trivyignore-validator
runs:
  using: "composite"
  steps:
    - run: bash --version
      shell: bash
    - run: ${GITHUB_ACTION_PATH}/src/action.sh
      shell: bash
