---
name: trivyignore-validator
description: trivyignore-validator
runs:
  using: 'composite'
  steps:
    - run: |
        filename=.trivyignore
        if test -f ${filename}; then
          echo "found a ${filename} file...";

          while read -r line; do
            if echo ${line} | grep -qE "^CVE\-"; then
              echo "found a 'CVE-' entry in the ${filename}...";
              echo "checking whether an expiry has been attached..."
              if ! echo ${line} | grep -qE "^CVE\-.*exp:[0-9]{4}(\-[0-9]{2}){2}$"; then
                echo "no expiry associated to: '${line}'. Add it by adding: 'exp:yyyy-mm-dd'"
                exit 1
              fi

              echo "checking whether the expiry will take place in one month..."
              current=$(echo "${line}" | sed -e "s|CVE.*exp:\(.*\)|\1|g")
              max=$(date +"%F" --date="$(date +%F) next month")
              if [[ "${current}" > "${max}" ]]; then
                echo "current date: '${current}' in line: '${line}' exceeds"
                echo "the maximum date of one month. Choose a new date that is"
                echo "before: ${max}"
                exit 1
              fi
            fi
          done < "${filename}"

          exit 0
        fi

        echo "no ${filename} file found"
      shell: bash
